#!/bin/bash

# Install nginx if not already installed
if ! command -v nginx &> /dev/null; then
    apt-get -y update
    apt-get -y install nginx
fi

# Create the redirection configuration file
echo "
server {
    listen 80;
    listen [::]:80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
" > /etc/nginx/sites-available/redirect

# Enable the redirection site
ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Remove the default site
rm /etc/nginx/sites-enabled/default

# Restart nginx
service nginx restart

