#!/usr/bin/env bash
apt-get update
apt-get install -y net-tools curl
service nginx status >/dev/null 2>&1 || service nginx start
netstat -tuln | grep 80 || sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
service nginx restart

